ALTER TABLE `%PREFIX%t_unt` ADD `build` INT(15) UNSIGNED NULL DEFAULT NULL AFTER `type`;
ALTER TABLE `%PREFIX%t_unt` ADD FOREIGN KEY (`build`) REFERENCES `%PREFIX%t_builds`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
UPDATE `%PREFIX%conf` SET `sge_ver`= 139 WHERE `sge_ver`= 138;